### ISSUE TITLE
MCM Out-Of-Tree Extensibility

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/machine-controller-manager#178]
### Problem

There are at least four possible approaches for out-of-tree drivers as documented in this [proposal](https://github.com/gardener/machine-controller-manager/pull/169).

1. MCM as GRPC server and the driver as GRPC client using bidirectional streaming over long-running GRPC connections (established by the driver during registration) for communication.
1. MCM as GRPC client and the driver as GRPC server using non-streaming regular GRPC calls.
1. Drivers as webhooks with MCM making calls to the driver webhook using some REST API.
1. Drivers a controllers.

We have implemented option 1 already as a PoC. Now we need to discuss and decide on the right approach.

#### MCM as GRPC server and driver as GRPC client
* Pros
  * Already [implemented](https://github.com/gardener/machine-controller-manager/blob/grpc-driver/cmd/external-aws-client/external-aws-client.go).
  * Can work even with `SecretRef` and `CloudConfig` not standardised in the `MachineClass` spec.
  * Enables caching of `MachineClass`, `Secret` and `CloudConfig` if necessary.
  * More secure? Only MCM needs to expose a GRPC endpoint.
  * Drivers can work as sidecar containers or as sidecar `deployments`.
  * Cluster administrator can control drivers' access to `kube-apiserver` and if necessary block it completely.
* Cons
  * Complex and potentially confusing design involving streaming API.
  * Implementing the driver could be complex as it involves handling the streaming messages.
* Mitigation
  * The complexity can be mitigated by writing a GRPC-based [call-back framework](https://github.com/gardener/machine-controller-manager/blob/grpc-driver/pkg/driver/grpc/client/provider.go) which can be used by driver implementation so that they can concentrate on the [cloud-provider side](https://github.com/gardener/machine-controller-manager/blob/grpc-driver/pkg/external/driver/aws/aws.go) without having to worry about the GRPC and MCM.

#### MCM as GRPC client and the driver as GRPC server
* Pros
  * Simpler design involving non-streaming regular GRPC calls.
  * This approach might be similar to the approach taken in CSI etc.
  * Drivers can work as sidecar containers or as sidecar `deployments`.
  * Cluster administrator can control drivers' access to `kube-apiserver` and if necessary block it completely.
* Cons
  * There are subtle differences in the requirements for out-of-tree drivers and those for CSI. For example, multi-tenancy.
  * Requires that `SecretRef` and `CloudConfig` are standardised in the `MachineClass` spec.
  * Caching of `MachineClass`, `Secret` and `CloudConfig` would be hard.
  * Less secure? Drivers need to expose a GRPC endpoint.
  * Implementing a driver would still be complex as it involves implementing a secure GRPC server.
* Mitigation  
  * Complexity can be mitigated by providing a GRPC-based call-back framework similar to [option 1](https://github.com/gardener/machine-controller-manager/blob/grpc-driver/pkg/driver/grpc/client/provider.go) which can be used by driver implementation so that they can concentrate on the [cloud-provider side](https://github.com/gardener/machine-controller-manager/blob/grpc-driver/pkg/external/driver/aws/aws.go) to enable the driver implementation to concentrate on the cloud-provider side without having to worry about the GRPC and MCM.
  * Difficulty in enabling caching and flexibility without having the `SecretRef` and `CloudConfig` standardised in the `MachineClass` can be mitigated by making the MCM *also* a GRPC server (*in addition* to the drivers as GRPC server) to expose API to fetch `MachineClass`, `Secret` and `CloudConfig`.

#### Drivers as webhooks
* Pros
  * Simpler design and REST API has a lower barrier for entry than GRPC.
  * Cluster administrator can control drivers' access to `kube-apiserver` and if necessary block it completely. But this would have some implications on the mitigations below.
* Cons
  * Requires that `SecretRef` and `CloudConfig` are standardised in the `MachineClass` spec.
  * Caching of `MachineClass`, `Secret` and `CloudConfig` would be practically impossible.
* Mitigation
  * The only possible mitigation for not having the `SecretRef`, `CloudConfig` standardised in the `MachineClass` would be by making the driver fetch these from the `kube-apiserver` directly. But this would not only break the webhook pattern but also defeat the very purpose of having a driver framework and the fourth option might be better suited.

#### Drivers as controllers
* Pros
  * Already [adopted](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/cloud/aws/controllers/machine/controller.go) in the cluster-api community.
  * Common design-pattern in Kubernetes and does not introduce new patterns/frameworks.
  * Cluster administrator can control drivers' access to `kube-apiserver` but not block it completely.
  * Support from cloud providers like the [AWS Service Operator](https://github.com/awslabs/aws-service-operator) make this approach more attractive.
* Cons
  * Writing a controller is complex.
  * Some access to `kube-apiserver` would be required from the drivers (read access to `Machines`, `MachineClasses`, `Secrets` and `CloudConfigs` and write access to the `Status` sub-resource of `Machines`).
  * MachineController (at least the cloud-provider-specific parts) would have to be separated out of MCM image.
* Mitigation
  * Complexity of writing a controller can be mitigated by writing a control-loop-based call-back framework similar to [option 1](https://github.com/gardener/machine-controller-manager/blob/grpc-driver/pkg/driver/grpc/client/provider.go) which can be used by driver implementation so that they can concentrate on the [cloud-provider side](https://github.com/gardener/machine-controller-manager/blob/grpc-driver/pkg/external/driver/aws/aws.go) instead of the complexity of writing a controller.
  * The need to have some minimal access to `kube-apiserver` from the drivers cannot be mitigated.
  * The MachineController (at least the cloud-provider-specific parts) can be separated into a separate image and the rest of MCM into a separate image.

**Comment by amshuman-kr** [comment]
@ggaurav10 You can copy this content to your proposal if you want ;-)

**Comment by ggaurav10** [comment]
Thanks for summarising @amshuman-kr.
I have added link to this in the doc. PR - #169

**Comment by amshuman-kr** [comment]
Current status:

1. MCM as GRPC server and driver as GRPC client - already implemented [here](https://github.com/gardener/machine-controller-manager/tree/grpc-driver) by @ggaurav10, @prashanth26 and @amshuman-kr.
1. MCM as GRPC client and the driver as GRPC server - @hardikdr intends to try this approach to see how this compares with option 1 above.

**Comment by amshuman-kr** [comment]
FWIW "Drivers as controllers" options makes the most sense.

**Comment by afritzler** [comment]
Was there a decision on which option to follow here? I am currently working on a POC for the OpenStack out-of-tree implementation (similar to the one we have for AWS in the Gardener org) and was asking myself if I should move this any further.

**Comment by prashanth26** [comment]
The decision was to implement the - _MCM as GRPC client and the driver as GRPC server (CSI approach)_. @hardikdr has been working on this. He would be the right person to answer your query. 

> similar to the one we have for AWS in the Gardener org

Which repo to you refer to by this? This one - https://github.com/gardener/machine-controller-manager-provider-aws?

**Comment by afritzler** [comment]
Exactly this one.

**Comment by hardikdr** [comment]
Sorry for late response.
Basically, as Prashanth mentioned - we may have drivers behaving as a gRPC server and MCM being client - I did a quick PoC here: https://github.com/hardikdr/mcm-drivers
- Need to test and improve further though.

**Comment by afritzler** [comment]
Thanks for the update! I basically took the gRPC client version of the AWS implementation and did the OpenStack port on my flight back from KubeCon. I will hold off with publishing it then and wait until we have a final agreement of how to proceed here.

**Comment by prashanth26** [comment]
Hi everyone,

After several rounds of discussion on the approach to be taken on OOT. We have decided to rework the existing OOT implementation to go with the controller based approach (4). The main reason for this being that the controller approach would provide more flexibility than the current gRPC approach which is in the works. We shall be making amends to the OOT implementation to accomodate this controller based implementation in the coming weeks. I shall update this issue with an PR to illustrate the changes.

**Comment by prashanth26** [comment]
## Solution
The solution decided on is option-4 above

## Acceptance Criteria
- [x] A new set of APIs (aligned with cluster API) to be decided on
- [x] Splitting of binaries into MCM & Drivers
- [ ] Refactoring and release
   - [x] Refactor unit tests for MCM
   - [ ] Merge `MCM/splitting-controllers2` [PR #460](#460 ) with master. 
   - [ ] Refactor integration tests for MCM
   - [ ] Refactor CI script for new MCM
   - [ ] New Release for `machine-controller-manager-provider-aws`
   - [ ] New MCM release - 0.30.0 [Issue #230](https://github.com/gardener/machine-controller-manager/issues/230). 
     - [x] Align with new APIs
     - [x] Retry logic to be introduced in MCM
     - [x] Improve creation & deletion logic of MCM - #349, #350 
     - [ ] Documentation for adding new provider support
- [ ] Migration Plan
- [ ] Implemented out-of-tree for existing providers and integrate into Gardener
    - [x] Vsphere
       - [x] Implementation
       - [x] Validation
       - [x] Unit Tests
    - [x] AWS
       - [x] Implementation
       - [x] Validation
       - [] Unit Tests
    - [ ] GCP
       - [ ] Implementation
       - [ ] Validation
       - [ ] Unit Tests
    - [ ] Alicloud
       - [x] Implementation
       - [ ] Validation
       - [ ] Unit Tests
    - [ ] Azure
       - [ ] Implementation
       - [ ] Validation
       - [ ] Unit Tests
    - [ ] Openstack
       - [ ] Implementation
       - [ ] Validation
       - [ ] Unit Tests
    - [ ] Packet
       - [ ] Implementation
       - [ ] Validation
       - [ ] Unit Tests

## Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by hoeltcl** [comment]
@vlerenc Why is it closed?

**Comment by prashanth26** [comment]
You are right @hoeltcl . This epic is still on going. /reopen

**Comment by prashanth26** [comment]
/close
The migration to OOT providers is complete.

However, there are small clean up tasks leftover like 

1. Move drain controller to a separate controller - https://github.com/gardener/machine-controller-manager/issues/621
2. Get rid of the deprecated in-tree machine controller - https://github.com/gardener/machine-controller-manager/issues/622
3. Adopt the integration tests - https://github.com/gardener/machine-controller-manager/issues/216
