### ISSUE TITLE
Integration test framework for MCM

### ISSUE THREAD

**Issue by PadmaB** [gardener/machine-controller-manager#216]
# Story
As machine-controller-manager developer I want to run a set of integration tests that are easy to validate breaking PRs. This framework must be golang based can be easily expanded to add new tests. 

# Motivation
Currently, we have a [bash based integration tests (IT) here](https://github.com/gardener/machine-controller-manager/blob/master/.ci/integration-tests). We would like to have completely refined integration tests for MCM using Golang tests. 

The idea would be to have a robust test environment, automates machine/machineSet/machineDeployment creation/deletion and such operations making it is easy for developers to run their tests in an integrated environment, publishing the results. 

# Acceptance Criteria
- [ ] A Golang Framework to accommodate a robust set of integration tests that can be easily adapted. 
- [ ] Ensure the end-to-end automation
- [ ] Validate the results
- [ ] Integrate the existing tests into TestMachinery. Refer - [gardener extension GCP](https://github.com/gardener/gardener-extension-provider-gcp/blob/master/test/integration/infrastructure/infrastructure_test.go), [etcd backup restore tests](https://github.com/gardener/etcd-backup-restore/blob/master/test/e2e/integration/cloud_backup_test.go)

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Integration tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added/changed public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [ ] User documentation: Have you updated the READMEs/docs/how-tos about user-relevant changes?

**Comment by prashanth26** [comment]
Adopt the test framework to the out of tree code style.
