### ISSUE TITLE
Machine Controller Manager Support in Cluster Auto Scaler

### ISSUE THREAD

**Issue by vlerenc** [gardener/machine-controller-manager#25]
# Story
- As user/operator I want to run as many machines as required for my workload, but no more, so that I am neither involved for scale-up (to ensure business continuity) nor for scale-down (to reduce costs).

# Motivation
In order to bring shoot cluster auto-scaling on all infrastructures to our users with our new machine controller manager, we need to adapt the [cluster autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) to support our new machine controller manager.

# Acceptance Criteria
- [x] New required machines are provisioned via the cluster autoscaler automatically
- [x] Not used machines are deprovisioned via the cluster autoscaler automatically
- [x] If it can only be done in a fork (see below), we can still consume upstream changes easily

# Implementation Proposal
We are already in discussion with the cluster and machine API working groups (we are part of them) and also with the folks from the cluster autoscaler, but the latter want to start work only if the first have agreed on the API, which is pretty late for us. As much as we don't like that, let's fork the cluster autoscaler therefore and integrate our machine controller manager, which should be a relatively well contained change (after all, our abstraction is quite minimal) allowing us to still consume upstream changes easily.

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?
- [ ] User documentation: Have you informed Sylvia Pick about user relevant changes?

**Comment by prashanth26** [comment]
The integration of CA to support MCM is done. 
Refer: https://github.com/gardener/autoscaler/commits/6f9a4ac90b79ffcb66097bb85246487d8a1af093

**Comment by prashanth26** [comment]
Closing this issue, as cluster-autoscaler has been modified to interact with MCM. Refer - https://github.com/gardener/autoscaler/releases/tag/v0.1.0

Also it has been intergrated with Gardener. Refer - https://github.com/gardener/gardener/pull/200
