### ISSUE TITLE
[GEP-31] Support `InPlaceUpdate` deployment strategy

### ISSUE THREAD

**Issue by acumino** [gardener/machine-controller-manager#944]
**How to categorize this issue?**

/area open-source
/kind enhancement
/priority 2

**What would you like to be added**:
As of now, machine deployment provides two strategies called `Recreate` and `RollingUpdate`, we would like to have new strategy called InPlaceUpdate, with two flavors `Auto` and `Manual` which should work as follows - 

## InPlaceUpdate: 
The following step will be performed for in-place update on the machine:
  - Mark the machine as unschedulable.
  - Drain the node.
  - Mark the machine as ready for an update using a set of labels/annotations.
  - Wait for an annotation/label indicating that the machine has been updated.
  -  Once the update is detected move the machine to the new machine set.
  -  Uncordon the node successfully updated and moved to the new machine set.

### Auto:
Machines will be selected based on maxUnavailable and will go through the steps mentioned above.

### Manual:
Machines/nodes will be selected for updates based on certain labels, which the user has control over. This strategy gives users the flexibility to specify which machines/nodes should be updated by applying predefined labels. Once a machine is labeled, it will follow the same steps as the InPlace update. 

### Tasks
- **Machine Controller Manager** 
  - [x] API changes
    - [x] `MachineDeployment` https://github.com/gardener/machine-controller-manager/pull/962
    - [x] Introduce Label Constants and `MachineConfiguration` options https://github.com/gardener/machine-controller-manager/pull/970
  - [x] Introduce a new rolling strategy
    - [x] InPlaceUpdate
      - [x] Auto https://github.com/gardener/machine-controller-manager/pull/973
      - [x] Manual https://github.com/gardener/machine-controller-manager/pull/987
- **MCM-providers**: Vendor the new MCM and adapt changes to support the InPlace update.
  - [x] https://github.com/gardener/machine-controller-manager-provider-alicloud/pull/100. **Released with** [v0.13.0](https://github.com/gardener/machine-controller-manager-provider-alicloud/releases/tag/v0.13.0)
  - [x] https://github.com/gardener/machine-controller-manager-provider-aws/pull/192 **Released with** [v0.24.0](https://github.com/gardener/machine-controller-manager-provider-aws/releases/tag/v0.24.0)
  - [x] https://github.com/gardener/machine-controller-manager-provider-gcp/pull/153. **Released with** [v0.24.0](https://github.com/gardener/machine-controller-manager-provider-gcp/releases/tag/v0.24.0)
  - [x] https://github.com/gardener/machine-controller-manager-provider-azure/pull/185 **Released with** [v0.16.0](https://github.com/gardener/machine-controller-manager-provider-azure/releases/tag/v0.16.0)
  - [x] https://github.com/gardener/machine-controller-manager-provider-openstack/pull/259 **Released with** [v0.23.0](https://github.com/gardener/machine-controller-manager-provider-openstack/releases/tag/v0.23.0)

**Comment by acumino** [comment]
/close
All tasks completed.
